### PR TITLE
Bluestore: Adds per-store allocation/compression statistics

### PR DESCRIPTION
**Pull request by ifed01**

### CODE REVIEW

**Comment by liewegas** [comment]
should we use get_ondisk_length() instead of adding a clength field?  that way we are counting the amount of space on disk that gets consumed.. which is the real savings.

**Comment by liewegas** [comment]
For statfs, I think we should actually just define a totally new struct, store_statfs_t or something, and stop using struct statfs entirely.  That avoids having two structs, and statfs was never a great fit anyway.

**Comment by liewegas** [comment]
For persisting the stats, I think we can make a new prefix with a new merge operator that does addition on int64_t boundaries (i.e., treats the value as a int64_t array).  Then we can just commit our delta with each op and it'll all get compacted/merged away by rocksdb.

**Comment by ifed01** [comment]
> should we use get_ondisk_length() instead of adding a clength field? that way we are counting the >amount of space on disk that gets consumed.. which is the real savings.

What's about having 3 parameters for compressed data:
1) Original Size
2) Compressed Size
3) Allocated Size
?
This way one can estimate both real compression rate and allocation granularity overhead.
Another minor point for having clength is that we can read using actual blob length rather than allocated one, e.g. 4K instead of 64K.

**Comment by ifed01** [comment]
> For statfs, I think we should actually just define a totally new struct, store_statfs_t or something, and >stop using struct statfs entirely. That avoids having two structs, and statfs was never a great fit anyway.

Sound good, will do.

**Comment by liewegas** [comment]
:+1:

**Comment by ifed01** [comment]
Replaced with https://github.com/ceph/ceph/pull/9486

**Pull request closed without merging**
