### PR TITLE
mon: remove last trace of PGMap from MgrMonitor

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@liewegas

**Comment by liewegas** [comment]
I don't think we want the second patch?  until the require_luminous flag is set we'll still be pulling this info from PGMonitor, and then we'll switch over the pointer to the MgrMonitor one when the flag is set?

**Comment by liewegas** [comment]
It occurs to me, though, that we could simplify this by giving Monitor a PGMapDigest pointer that switches over, use that directly, and all the PGMonitor-specific stuff that is guarded by the luminous flag can continue to reach directly into PGMonitor like it did.  Then we lose to ceph_abort's in the PGStatService default implementations, though, so maybe it's better as is

**Comment by liewegas** [comment]
@gregsfortytwo

**Pull request merged**
