### PR TITLE
mon: handle MGetPoolStats using PGStatService 

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@liewegas 

sorry for this!

**Comment by tchaikov** [comment]
@liewegas this branch 

- is rebased on master
- folded your PGTempMap.basic test into the commit introducing more efficient PGMapTemp to OSDMap
- and includes:
> mon: handle MGetPoolStats using PGStatService  …			142f5f4

could you please reset your branch to this one?

**Comment by liewegas** [comment]
done

**Comment by tchaikov** [comment]
@liewegas ping?

**Comment by tchaikov** [comment]
https://github.com/ceph/ceph/pull/15073 does not contain 142f5f4 yet

**Comment by tchaikov** [comment]
0023a35 should address the failure of http://pulpito.ceph.com/kchai-2017-05-29_07:20:22-rados-wip-mgr-stats-kefu---basic-mira/1241403/

**Pull request merged**
